### ISSUE TITLE
Investigate malformed AQL query in multimatrix  

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet-api#137]
Here is the page that produces such error: https://multimatrix.multinet.app/?workspace=Jake%27s+Workspace&network=test

And here is the serialized AQL query that's sent over the wire

```
https://api.multinet.app/api/workspaces/Jake's Workspace/aql/?query=let+nodes+=+(FOR+n+in+[test--actors,test--films]
[**]+LIMIT+10+RETURN+n)+let+edges+=+(FOR+e+in+test--edgelist+filter+e._from+in+nodes[**]._id+
&&+e._to+in+nodes[**]._id+RETURN+e)++++++RETURN+{"nodes":+nodes[**],+edges}
```

With a response from the server of

```
"AQL: collection or view not found: test (while parsing)"
```

This may be due to an issue with serializing the AQL query in query params. If that's the case, I think switching the endpoint to a POST, and sending this data in the body would be sufficient.

**Comment by waxlamp** [comment]
> This may be due to an issue with serializing the AQL query in query params. If that's the case, I think switching the endpoint to a POST, and sending this data in the body would be sufficient.

Good idea.
