### ISSUE TITLE
Server Error (500) when logging in/creating account

### ISSUE THREAD

**Issue by JakeWags** [multinet-app/multinet-api#149]
This error does NOT occur when using a google account.

**Comment by JackWilb** [comment]
The solution will be to either enable email logins (this might require some infrastructure), or to disable it

**Comment by hassantarabai** [comment]
Hello,

Any update on this error . I noticed its still on, I tried log in or create a new account but always getting "Server error 500". I tried with my gmail, institution email and hotmail.
With all, am getting the same error message.

**Comment by JackWilb** [comment]
Hello, you need to do the oauth login. We will not be storing passwords with this application
