### ISSUE TITLE
Use chunked insert_many calls in Table.put_rows

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet-api#37]
In `Table.put_rows`, we're making a call to `python-arango`'s `Collection.insert_many` function:
https://github.com/multinet-app/multinet-api/blob/bdc8dd04a91954cd7a2dd1a05542ab476bf7d882/multinet/api/models/table.py#L61

For large amounts of documents this seems to take longer than 60 seconds, causing a timeout. In production, this was observed with a file with ~20K rows. In local testing, I had to increase that, and connect to the testing database so that some data was actually going over the network (otherwise you'd probably never observe this locally).

There are a couple of issues here:
* We should probably chunk the documents we want to send into reasonable sizes, so that each call to `insert_many` is not too large.
* In the call to `insert_many`, we specify `return_new=True`, so that in the response of the row upload endpoint, we can return the newly inserted documents with their arango metadata attached. While this works for small amounts of rows, it's a problem when dealing with large quantities, as it means that all of the data just sent has to be sent _back_ to the api, increasing the time of that request substantially (in my exact case, I think this is what is causing the timeout to actually occur, as the rows do end up in the database, so it seems the connection is open long enough for the database to retrieve the documents).
* Even if this call were to be completed in a short amount of time, it means that the row insertion endpoint would then be returning all of the documents inserted (~20K in my case), which is just too much to return from any endpoint.
* Even with a trivial amount of documents being sent (say ~1K), returning all of these documents from this endpoint at once would break the conventions we have in place for response pagination. 

I think a simple way to solve this would be the following:
* Chunk the calls to `insert_many`
* In the current row insertion endpoint, return just the number of documents inserted, along with any errors if they occur
* Add a search query parameter onto our current endpoint for retrieving rows, which we can pass into [`find`](https://github.com/multinet-app/multinet-api/blob/bdc8dd04a91954cd7a2dd1a05542ab476bf7d882/multinet/api/models/table.py#L57) command we use to retrieve rows from arango. This query param can be a dict, of the same syntax as a normal mongo-style find. So if you were looking for rows in an edge table with a certain connection, you could pass `{ "_from": "foo/bar" }` in that parameter.

That last change seems unrelated, but is included because if we change the response on the row insertion endpoint, there's no longer any association between a document and it's key/id in the database, aside from just retrieving all the rows and looking for it. So that change would maintain this feature in some way. 

Any thoughts on this @waxlamp?

**Comment by AlmightyYakob** [comment]
@waxlamp This also might be responsible for the crashed worker we saw when processing that large file the other day.

**Comment by waxlamp** [comment]
Thanks Jake. Will read, digest, and respond tomorrow.

**Comment by waxlamp** [comment]
> I think a simple way to solve this would be the following:
> 
> * Chunk the calls to `insert_many`

If you  have a PUT request that's timing out, why would chunking the calls to `insert_many()` help? I would imagine that would actually make the request take slightly longer due to the chunking overhead and the added overhead of each call.

Unless you meant that the client should do the chunking by performing several PUT operations--that makes sense to me, and we could add support for it in multinetjs.

> * In the current row insertion endpoint, return just the number of documents inserted, along with any errors if they occur

👍🏾, though this response could also be quite large if, e.g. in the extreme case, each row is malformed and generates an error. That might not arise in practice but it's worthwhile to think about the design in that edge case.

> * Add a search query parameter onto our current endpoint for retrieving rows, which we can pass into [`find`](https://github.com/multinet-app/multinet-api/blob/bdc8dd04a91954cd7a2dd1a05542ab476bf7d882/multinet/api/models/table.py#L57) command we use to retrieve rows from arango. This query param can be a dict, of the same syntax as a normal mongo-style find. So if you were looking for rows in an edge table with a certain connection, you could pass `{ "_from": "foo/bar" }` in that parameter.
> 
> That last change seems unrelated, but is included because if we change the response on the row insertion endpoint, there's no longer any association between a document and it's key/id in the database, aside from just retrieving all the rows and looking for it. So that change would maintain this feature in some way.

I'm not sure I follow. Do you mean that without returning the new documents, the client won't know what the ID is for the rows it has just uploaded?

I'm not opposed to this feature, though I don't know why you wouldn't simply use AQL to perform a row query, and leave the rows endpoint specifically for paging through all the rows of a table.

**Comment by AlmightyYakob** [comment]
> If you have a PUT request that's timing out, why would chunking the calls to `insert_many()` help? I would imagine that would actually make the request take slightly longer due to the chunking overhead and the added overhead of each call.
> 
> Unless you meant that the client should do the chunking by performing several PUT operations--that makes sense to me, and we could add support for it in multinetjs.

In the scenario I encountered, the celery task was calling `insert_many` when processing a CSV upload, so it wasn't a request to an endpoint of ours that was timing out, it was the request to arango (with all of the documents at once) that was timing out. You're right though, if you were uploading all of these rows through the API, the request would likely timeout there as well. However, that could happen under any circumstance, whether it be a large number of documents, the documents being large themselves, the client's upload speed being very slow, etc. The client always has the option to chunk its request if it wants to, and maybe we could enforce this in the client library. I still think chunking the requests to arango is beneficial, as it greatly reduces the chances of one of the timeouts occuring (the requests to arango).

> though this response could also be quite large if, e.g. in the extreme case, each row is malformed and generates an error. That might not arise in practice but it's worthwhile to think about the design in that edge case.

Yeah I'm not sure what a total solution would look like. I think the edge case where that endpoint returns a large amount of errors is an acceptable exception to our current pagination scheme. It's unlikely to occur often (or at all), and I don't think it's worth sinking time into until we encounter serious problems with the current approach.

> I'm not sure I follow. Do you mean that without returning the new documents, the client won't know what the ID is for the rows it has just uploaded?

Yes exactly.

> I'm not opposed to this feature, though I don't know why you wouldn't simply use AQL to perform a row query, and leave the rows endpoint specifically for paging through all the rows of a table.

To me there's a bit of a distinction. The filter on the row retrieval endpoint would just be a simpler way to filter the rows of a table, while the AQL endpoint is a more complex and fully featured way perform AQL queries at the workspace level. I don't see an issue with having both. What do you think?
