### ISSUE TITLE
Create endpoint for arbitrary AQL execution

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet-api#43]
This should be executed by the readonly user, and should be limited both in time and memory usage. [These](https://docs.python-arango.com/en/main/specs.html?highlight=execute#arango.aql.AQL.execute) `python-arango` docs show what parameters are used to apply these limits.

**Comment by waxlamp** [comment]
Is this closed by #71? You used the word "solves" in that PR description, but I don't think that's one of the [magic words](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) that closes a linked issue.

**Comment by naglepuff** [comment]
Yup, thanks for pointing that out.
