### ISSUE TITLE
Create standard way to catch task failures

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet-api#44]
Currently, if an exception is thrown and not caught manually in our tasks, the task ends, but the status and error messages aren't updated, leaving it in a perpetual `STARTED` state. We should come up with some standardized and simple way to wrap a task such that any exceptions lead to that task being marked as `FAILED`, and the exception message added to the task error messages.

One way this could be done is through using a custom decorator. We also may want to make better use of transactions (both [django](https://docs.djangoproject.com/en/3.2/topics/db/transactions/#controlling-transactions-explicitly) and [arango](https://docs.python-arango.com/en/main/transaction.html)), but this might be a slightly separate issue. The arango transactions might need to be placed within model methods (e.g. `Table.put_rows`) instead of the tasks themselves.

**Comment by waxlamp** [comment]
There must be a standard way to do this from the Girder4 side--could you check with the Slack channel and see what they say?

**Comment by AlmightyYakob** [comment]
> There must be a standard way to do this from the Girder4 side--could you check with the Slack channel and see what they say?

There is a standard way to deal with general failures and retries ([this](https://www.distributedpython.com/2018/09/04/error-handling-retry/) article provides an example), but since the tracking of the task status is custom to our app, I'm not so sure that has a specific "standard". I'll see what the other Girder4 folks say.

**Comment by AlmightyYakob** [comment]
After some discussion, it looks like Celery [Task Inheritance](https://docs.celeryproject.org/en/stable/userguide/tasks.html#task-inheritance) might be the way to go. We can put our logic around marking failed uploads in the `on_failure` method. We could even combine this with [autoretrying](https://docs.celeryproject.org/en/stable/userguide/tasks.html#automatic-retry-for-known-exceptions), as the `on_failure` method is only called after all retries have been run.
