### ISSUE TITLE
Failed upload tracking

### ISSUE THREAD

**Issue by waxlamp** [multinet-app/multinet-api#53]
We need some way to know about failed uploads, to display them in the client, to clear them (and their data) from the system, etc.

**Comment by AlmightyYakob** [comment]
Would a filter for status type on the `GET /uploads/` endpoint, and a `DELETE /uploads/{id}/` endpoint suffice here? Also, when mentioning clearing their data, does this include the arango collections/networks? What about the objects in S3?

**Comment by waxlamp** [comment]
> Would a filter for status type on the `GET /uploads/` endpoint, and a `DELETE /uploads/{id}/` endpoint suffice here?

Yes, I think so, along with client code to somehow display these downloads while they're going, if they fail, etc.

> Also, when mentioning clearing their data, does this include the arango collections/networks? What about the objects in S3?

I was specifically thinking of the S3 objects, not the data in Arango or Postgres. Essentially, we shouldn't just leave data in S3 if it's never going to wind up in Multinet.
