### ISSUE TITLE
Track network/table dependency

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet-api#55]
In the client, we have a [findDependentGraphs](https://github.com/multinet-app/multinet-client/blob/226042fa87151a9a73b2f427250ddc09312f385c/src/components/DeleteTableDialog.vue#L190-L226) function. This is something we could easily track in the api, by adding a `tables` field to the `Network` model, which would be a [`ManyToManyField`](https://docs.djangoproject.com/en/3.2/topics/db/examples/many_to_many/#many-to-many-relationships) between Networks and Tables.

The reason this doesn't currently exist is because during the initial design of the Girder4 api, I wanted to keep the separation of information very clear, and didn't want to muddy the waters between what information is stored in arango, and what's stored in postgres. At this point, we have a little more room to breathe, and can take time to determine if this is a good change or not.

The main required changes would be updating [`Network.create_with_edge_definition`](https://github.com/multinet-app/multinet-api/blob/0db673c7e4ebd8f204b59db9cbd99c9585eca232/multinet/api/models/network.py#L65-L85) to link the newly created network with any tables, as well as using the [`pre_delete`](https://docs.djangoproject.com/en/3.2/ref/signals/#pre-delete) signal to remove this relationship from any tables that the network used.

To make use of this, we might be able to just update the existing use of our table and network endpoints. For tables, the table detail endpoint could be updated to include the `network_set` field (from the reverse many-to-many relation). For networks, the same can mostly be done, except that we might want to split up the tables into `node_tables` and `edge_tables` at the serializer, to make it more clear.

@waxlamp thoughts?

**Comment by AlmightyYakob** [comment]
Another approach is to not track it at all in postgres, and to expose these endpoints / model methods that just query arango directly to determine these relationships. This might make the separation of information a bit cleaner, but would also require more application logic.

**Comment by waxlamp** [comment]
I like this idea. I am not totally sure of how safe it is the double encode relationships whose source of truth is in Arango into Postgres as well. I feel like we should do it (along the lines of implementation you've suggested) but that we'll also need to add some kind of `fsck` type of utility as a maintenance script that we can run to retrieve reports of any problems in our data store (i.e. things like orphaned Arango workspaces, orphaned tables, misaligned network-to-table mappings, etc.)

**Comment by waxlamp** [comment]
I think we decided to simply retrieve this dependency information from Arango as needed. Is that right, @AlmightyYakob? If so, can we close this issue?

**Comment by AlmightyYakob** [comment]
> I think we decided to simply retrieve this dependency information from Arango as needed. Is that right, @AlmightyYakob? If so, can we close this issue?

Correct.
