### ISSUE TITLE
Parameterize tests for permission levels

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet-api#56]
After all of the permissions PRs are settled, we should look into parameterizing tests based on permission level. Often in the tests, it seems we're writing separate tests for behavior that's mostly unchanged, except the user level, and whether the action being tested was actually completed (due to sufficient permissions), or failed (due to insufficient permissions). I think the following parameterization would be a good start (pseudo-code):

```python
@pytest.mark.parametrize("permission,status_code,success", [
	(None, 404, False),
	(WorkspacePermission.reader, 403, False),
	(WorkspacePermission.writer, 200, True),
	...,
])
def test_table_rest_insert_rows(..., user, permission, status_code, success):
	workspace.set_user_permission(user, permission)
	...

	r = client.put(...)	
	assert r == status_code
	if success:
		# assert that things have changed as desired
	else:
		# assert that nothing has changed
```

Thoughts @naglepuff @waxlamp?

**Comment by waxlamp** [comment]
Neat. Looks like a good idea if it works out this way when you go to do it.
