### ISSUE TITLE
Write a script to create the `readonly` Arango user

### ISSUE THREAD

**Issue by waxlamp** [multinet-app/multinet-api#57]

**Comment by AlmightyYakob** [comment]
This could likely be a [`manage.py`](https://docs.djangoproject.com/en/3.2/howto/custom-management-commands/) command, unless you see a better path forward.

**Comment by waxlamp** [comment]
I think that sounds like a good idea. You can validate that it's a good approach with #girder4.

**Comment by JackWilb** [comment]
This seems to be fixed with `./manage.py createarangoreadonlyuser`
