### ISSUE TITLE
Add "table" type information

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet-api#6]
This would be accomplished by having a ColumnType model, with the structure:

```
class ColumnType(TimeStampedModel):
    column = models.CharField(max_length=100)
    type = <Django choice for each type>
    table = models.ForeignKey(Table, related_name='columns', on_delete=models.CASCADE)
```

**Comment by AlmightyYakob** [comment]
This is solved for upload via [`ColumnTypeEnum`](https://github.com/multinet-app/multinet-api/blob/bdc8dd04a91954cd7a2dd1a05542ab476bf7d882/multinet/api/tasks/process/utils.py#L11-L20). No type information is explicitly stored in the database, but some of it is implicitly stored via the data itself. If we care about retrieving this type info, there is more work to be done here.

**Comment by waxlamp** [comment]
This is probably good enough for now. It may be the case that we want to enable searching columns by type of something in the future, or some other need would arise. But if you're satisfied with the current state of things, we can close.
