### ISSUE TITLE
Create endpoints for retrieving the current user's permission

### ISSUE THREAD

**Issue by naglepuff** [multinet-app/multinet-api#60]
See [RFC #0013](https://github.com/multinet-app/multinet-rfcs/tree/master/0013-getting-user-permissions) for details regarding this issue.

It would be helpful for client applications to know what the permission level of the current user for a given workspace is. This would allow hiding/displaying of elements like buttons based on the logged-in user's permission level. A new endpoint should be added for this.

The endpoint could look something like this:
`/api/workspaces/{workspace_name}/permissions/{user_name}/`

(the RFC suggests a different looking endpoint, I'm open to further discussion)

It would return `404` if the user has no permission and the workspace is private. If the user has no explicit permission and the workspace is public, then a value representing the **reader** level should be returned. Otherwise, return the permission level of the user.

**Comment by AlmightyYakob** [comment]
I think we should go with `/api/workspaces/{workspace}/permissions/me` for the endpoint. The user can't check the permissions of other users, so just sticking `/me` on the end should be fine.
