### ISSUE TITLE
Add a download route to get data from client applications

### ISSUE THREAD

**Issue by JackWilb** [multinet-app/multinet-api#92]
This should allow specifying a filter so that the data that's shown can be downloaded, instead of the whole table

**Comment by AlmightyYakob** [comment]
What do you mean by "data that's shown"?

**Comment by JackWilb** [comment]
Say you filter a twitter network down to all people under 40 years old. We could have a way to specify this kind of query to the API so that it can give us a download with only the matching rows

**Comment by AlmightyYakob** [comment]
I see. If the format isn't important, this could probably be achieved through the AQL endpoint, couldn't it?

**Comment by JackWilb** [comment]
Yeah, maybe we should move this to multinetjs so that we can have some consistent logic there to handle the filtering and converting it to an AQL query for download

**Comment by waxlamp** [comment]
> Yeah, maybe we should move this to multinetjs so that we can have some consistent logic there to handle the filtering and converting it to an AQL query for download

Depending on what you need in the short term, this issue could be perfectly valid here.

What specific requirements do you have, based on use cases you've run into?

**Comment by JackWilb** [comment]
So I've noticed that these endpoints don't exist and the client is 404ing. Getting this fixed will fix some of the broken functionality on the client, and is likely necessary for our release.

My original thought was that these endpoints should also be used in the visualization apps to reduce the amount of code we'd need to maintain. That would mean that these endpoints would need to support the querying, filtering, and selections that the apps do. Using AQL is likely the way we'll handle that on the clients to update the visualizations, so we can use that similar logic to create the networks to download.

**Comment by JackWilb** [comment]
Closed via https://github.com/multinet-app/multinet-client/pull/279
